# Generated by Django 4.2.16 on 2024-11-06 11:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='GB'),
        ),
    ]
