# Generated by Django 4.2.16 on 2024-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
